python3 process/consumer.py interred1ah.txt &
python3 process/consumer.py interred1aj.txt &
python3 process/consumer.py interred1ai.txt &
python3 process/consumer.py interred1ai.txt &
python3 process/consumer.py interred1af.txt &
python3 process/consumer.py interred1ag.txt &
python3 process/consumer.py interred1ad.txt & 
python3 process/consumer.py interred1ae.txt & 
python3 process/consumer.py interred1aj.txt & 
python3 process/consumer.py interred1ae.txt & 
python3 process/consumer.py interred1aa.txt &