python3 process/insertsM.py interredes0aa.txt &
python3 process/insertsM.py interredes0ab.txt &
python3 process/insertsM.py interredes0ac.txt &
python3 process/insertsM.py interredes0ad.txt &
python3 process/insertsM.py interredes0ae.txt &
python3 process/insertsM.py interredes0af.txt &
python3 process/insertsM.py interredes0ag.txt &
python3 process/insertsM.py interredes0ah.txt &
python3 process/insertsM.py interredes0ai.txt &
python3 process/insertsM.py interredes0aj.txt &
python3 process/insertsM.py interredes0ak.txt &
python3 process/insertsM.py interredes0al.txt &
python3 process/insertsM.py interredes0am.txt &
python3 process/insertsM.py interredes0an.txt &
python3 process/insertsM.py interredes0ao.txt &
python3 process/insertsM.py interredes0ap.txt &
python3 process/insertsM.py interredes0aq.txt &
python3 process/insertsM.py interredes0ar.txt &
python3 process/insertsM.py interredes0as.txt &
python3 process/insertsM.py interredes0at.txt &